name: run rest-assured todo project

on:
  push:
    branches: [ "master" ]


jobs:
  testJob:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: 'temurin'
          cash: maven
      - run: mvn clean test